// Company hiring-process outlines shown on /companies and /companies/:id.
// A hand-written entry for the best-known recruiters, then generated
// entries for the rest from a per-category template. Each company is
// [id, name, category, summary, rounds ("Title|detail"), topics, tip].

export const COMPANY_DISCLAIMER =
  "Typical outline of rounds, based on publicly shared information and common patterns for each type of company. The actual process, order and difficulty vary by company, role, year and campus. Always check the official careers page. Anobyt is not affiliated with these companies.";

const CO = [
['tcs','TCS','IT Services','Large-scale IT services hiring through the TCS NQT drive.',['Online assessment|TCS NQT with numerical, verbal and reasoning sections plus a programming section.','Technical interview|Projects, programming basics, DBMS, OS and your core subjects.','Managerial interview|Problem-solving approach, teamwork and situational questions.','HR interview|Communication, relocation and joining details.'],'Aptitude, C / Java / Python basics, DBMS and SQL, OOP, Your projects','Know every line of your resume and project. Interviewers start there.'],
['infosys','Infosys','IT Services','Mass recruiter with separate tracks for general and specialist programmer roles.',['Online assessment|Reasoning, mathematical ability, verbal ability and pseudocode-style questions.','Coding round|Timed problems for specialist roles, with more DSA depth at higher tiers.','Technical interview|Fundamentals, projects and a coding discussion.','HR interview|Communication, mindset and role fit.'],'Aptitude, Pseudocode, DSA basics, DBMS, Java / Python','Practice pseudocode tracing. It decides many first-round results.'],
['wipro','Wipro','IT Services','IT services hiring through an online assessment followed by interviews.',['Online assessment|Aptitude, logical reasoning, verbal ability and a coding section.','Written communication|A short email or essay test in some drives.','Technical interview|Programming basics, projects and CS fundamentals.','HR interview|Behavioral and company-fit questions.'],'Aptitude, Verbal ability, Programming basics, CS fundamentals','Write a clear, error-free email. Communication is screened early.'],
['cognizant','Cognizant','IT Services','Campus hiring for associate roles, including the GenC programs.',['Online assessment|Aptitude, technical MCQs and a communication check.','Coding round|Basic to medium problems for higher-paying profiles.','Technical interview|Projects and fundamentals.','HR interview|Communication and attitude.'],'Aptitude, Technical MCQs, Basic coding, Communication','Be consistent on fundamentals. Cut-offs are applied per section.'],
['accenture','Accenture','IT Services','Consulting and technology services with a multi-stage assessment.',['Cognitive and technical assessment|MCQs on reasoning, pseudocode, networking, cloud and other basics.','Coding round|Programming problems in a timed environment.','Communication assessment|Spoken and written English evaluation.','Interview|Technical and HR discussion.'],'Pseudocode, Networking basics, Cloud basics, Coding, English communication','Practice speaking answers out loud. The communication round is a real filter.'],
['capgemini','Capgemini','IT Services','Global IT services firm with game-based screening for freshers.',['Game-based and aptitude round|Logic and cognitive games plus aptitude.','Pseudocode and technical MCQs|Programming logic and CS basics.','Communication assessment|English speaking and listening.','Technical and HR interview|Projects, basics and fit.'],'Logical reasoning, Pseudocode, CS basics, English communication','Stay calm in the game round. Accuracy matters more than speed.'],
['hcl','HCLTech','IT Services','IT and engineering services recruiter with an online screening round.',['Online assessment|Aptitude, logical reasoning and technical sections.','Technical interview|Core programming, DBMS and projects.','HR interview|Communication and background.'],'Aptitude, Programming, DBMS, Projects','Prepare a crisp two-minute introduction.'],
['techm','Tech Mahindra','IT Services','Telecom-focused IT services company hiring freshers through campus drives.',['Online assessment|Aptitude, reasoning, English and basic technical questions.','Technical interview|Projects and fundamentals.','HR interview|Fit, location and joining.'],'Aptitude, English, Basic technical questions, Projects','Revise basics of your branch along with programming.'],
['amazon','Amazon','Product','Product company with coding-heavy hiring and a strong behavioral component.',['Online assessment|Coding problems plus a work-style or work-simulation section.','Technical interviews|DSA problem solving on a shared editor, with follow-ups on complexity.','Behavioral round|Stories mapped to the leadership principles.','Bar-raiser round|An experienced interviewer from another team checks the overall hiring bar.'],'Arrays and strings, Trees and graphs, Dynamic programming, OOP and design, Leadership principles','Prepare six to eight real stories you can adapt to different behavioral questions.'],
['google','Google','Product','Product company known for deep problem-solving interviews.',['Resume screen and online round|Shortlisting and, in some cases, an online coding assessment.','Phone or video screen|One coding problem with discussion.','Onsite or virtual loop|Several rounds of DSA and problem solving, plus system design for experienced roles.','Googleyness and leadership|Behavioral and collaboration questions.'],'Data structures, Algorithms, Complexity analysis, Clean code, Communication','Think aloud. Interviewers evaluate how you reason, not only the final code.'],
['microsoft','Microsoft','Product','Product company with DSA-focused technical rounds and a manager conversation.',['Online coding round|Timed problems from common DSA topics.','Technical interviews|Data structures, algorithms and design discussion.','Hiring manager round|Projects, decision-making and role fit.'],'Arrays and strings, Linked lists, Trees, Recursion, Object-oriented design','Explain trade-offs between two solutions before you code.'],
['deloitte','Deloitte','Consulting','Professional services firm hiring analysts and technology consultants.',['Online assessment|Aptitude, reasoning and sometimes technical MCQs.','Technical interview|Role-based questions on programming, databases and projects.','HR and managerial interview|Communication, client mindset and teamwork.'],'Aptitude, Logical reasoning, Programming, Databases, Business communication','Show structured thinking. Consulting interviews reward clear frameworks.'],
['salesforce','Salesforce','Product','Cloud software company with technical and values-based interviews.',['Online assessment|Coding and problem-solving.','Technical interviews|DSA, CS fundamentals and projects.','Hiring manager and behavioral round|Collaboration, ownership and values.'],'Data structures, Algorithms, DBMS and SQL, OOP, Behavioral stories','Learn what the company does and be ready to explain why you want to join.']];
const TPL = {
i:{b:' is an IT and digital services company that hires freshers through campus and off-campus drives.',r:['Online assessment|Aptitude, reasoning, verbal ability and basic coding or technical MCQs.','Technical interview|Projects, programming basics, DBMS and core subjects.','HR interview|Communication, relocation and joining details.'],t:'Aptitude, Verbal ability, Programming basics, DBMS and SQL, Your projects',p:'Clear the online assessment cut-offs first, then be ready to explain every project on your resume.'},
p:{b:' is a technology product company that hires engineers through coding-focused interviews.',r:['Online coding assessment|Timed DSA problems on a coding platform.','Technical interviews|Data structures, algorithms and problem solving with follow-ups on complexity.','Design or projects round|Low-level design, OOP or a deep dive into your projects.','Hiring manager round|Behavioral questions, motivation and team fit.'],t:'Arrays and strings, Trees and graphs, Dynamic programming, OOP and design, Your projects',p:'Practice solving problems aloud and explain trade-offs before you write code.'},
c:{b:' is a professional services firm that hires analysts and technology consultants.',r:['Online assessment|Aptitude, reasoning and sometimes technical MCQs.','Technical or case interview|Role-based questions or a structured business problem.','Managerial and HR interview|Communication, client mindset and teamwork.'],t:'Aptitude, Logical reasoning, Communication, Basic technical skills',p:'Structure your answers clearly. Consulting interviews reward organised thinking.'},
s:{b:' is a strategy consulting firm with a highly selective, case-based hiring process.',r:['Application and screening|Resume and academic shortlisting.','Online assessment|A problem-solving or aptitude assessment. The format varies by firm.','Case interviews|Structured business problems solved live with the interviewer.','Final round|Further cases plus fit and motivation questions.'],t:'Case frameworks, Market sizing, Mental maths, Structured communication',p:'Practice cases out loud with a partner and learn to structure before you calculate.'},
a:{b:' is an analytics and data science firm that hires graduates for analyst roles.',r:['Online assessment|Aptitude, logical reasoning, SQL or analytics questions and guesstimates.','Technical or case interview|Statistics, SQL, Python and a business problem.','HR and managerial interview|Communication and role fit.'],t:'Aptitude, SQL, Statistics, Python, Case thinking',p:'Brush up on SQL joins and basic statistics. Both come up often.'},
f:{b:' is a financial services company that hires technology graduates for engineering and analyst roles.',r:['Online assessment|Aptitude and coding or technical MCQs.','Technical interviews|DSA, DBMS, OOP and a discussion of your projects.','Managerial and HR round|Communication, motivation and fit for the team.'],t:'Data structures, Algorithms, DBMS and SQL, OOP, Puzzles and probability',p:'Be ready for coding as well as logical and probability puzzles.'},
e:{b:' is a consumer technology company that hires engineers who can build and ship quickly.',r:['Online coding round|DSA problems on a coding platform.','Technical interviews|DSA and a discussion of your projects.','Hiring manager round|Ownership, culture fit and role expectations.'],t:'Arrays and strings, Hashing, Trees, Your projects, System basics',p:'Have one project you can explain end to end, including the trade-offs you made.'},
k:{b:' hires engineers for hardware, embedded, telecom and core engineering roles.',r:['Online aptitude and technical test|Aptitude plus core subject MCQs for your branch.','Technical interviews|Core subjects such as digital electronics, C and embedded basics, plus projects.','HR interview|Communication, location and joining details.'],t:'Digital electronics, C programming, Embedded basics, Core branch subjects, Your projects',p:'Revise your core branch subjects. Interviewers go deep on what is on your resume.'}};
const G = {
i:['LTIMindtree','Mphasis','Hexaware','Persistent Systems','Zensar','Coforge','Birlasoft','Mastek','Sonata Software','Virtusa','DXC Technology','NTT DATA','Genpact','Concentrix','EXL','WNS','IBM','Atos','Kyndryl','CGI','Cyient'],
p:['Adobe','Oracle','SAP','Cisco','Intuit','Atlassian','Uber','Walmart Global Tech','Meta','Apple','ServiceNow','Workday','Dell Technologies','HP','VMware','Zoho','Freshworks','LinkedIn','Nutanix','NetApp','Arista Networks'],
c:['EY','KPMG','PwC'],s:['McKinsey & Company','Boston Consulting Group','Bain & Company','Kearney','Oliver Wyman'],a:['ZS Associates','Mu Sigma','Fractal Analytics','Tiger Analytics','LatentView Analytics'],
f:['Goldman Sachs','Morgan Stanley','JPMorgan Chase','Barclays','Deutsche Bank','Citi','Wells Fargo','American Express','Standard Chartered','HSBC','BNY Mellon','State Street','Fidelity Investments','Bank of America','UBS','Nomura','Visa','Mastercard','PayPal','HDFC Bank','ICICI Bank','Razorpay','PhonePe','Paytm'],
e:['Flipkart','Myntra','Swiggy','Zomato','Meesho','Ola','CRED','Nykaa'],
k:['Intel','NVIDIA','Qualcomm','AMD','Texas Instruments','Micron','Cadence','Synopsys','Siemens','Honeywell','Bosch','Samsung R&D','Schneider Electric','ABB','Larsen & Toubro','Tata Elxsi','Ericsson','Nokia','Reliance Jio','Bharti Airtel','Broadcom']};
const CN = {i:'IT Services',p:'Product',c:'Consulting',s:'Consulting',a:'Consulting',f:'Fintech & Banking',e:'E-commerce',k:'Core & Telecom'};
Object.keys(G).forEach(function(k){G[k].forEach(function(n){var id=n.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');if(CO.some(function(x){return x[0]==id||x[1]==n}))return;var t=TPL[k];CO.push([id,n,CN[k],n+t.b,t.r,t.t,t.p])})});

export const COMPANY_CATEGORIES = ["All", "IT Services", "Product", "Consulting", "Fintech & Banking", "E-commerce", "Core & Telecom"];

export const COMPANIES = CO.map(([id, name, category, summary, rounds, topics, tip]) => ({
  id,
  name,
  category,
  summary,
  rounds: rounds.map((r) => {
    const [title, detail] = r.split("|");
    return { title, detail };
  }),
  topics: topics.split(", "),
  tip,
}));

export const ROUNDS_MAPPED = COMPANIES.reduce((n, c) => n + c.rounds.length, 0);

export function getCompany(id) {
  return COMPANIES.find((c) => c.id === id);
}
